apiVersion: v1
kind: Pod
metadata:
  name: pod-storage-demo
spec:
  containers:
    - name: nginx
      image: nginx
      VolumeMounts:
        - mountPath: /usr/share/nginx/html
        - name : html
    - name: debug
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      VolumeMounts:
        - mountPath: /mnt
        - name: html


    - volumes:
        - name: html
          emptyDir: {}