# Replica set
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
  labels:
    project: example
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.2
---
apiVersion: v1
kind: Pod
metadata:
  name: p3
  labels:
    project: example
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx