apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
data:
  DEMO_GREETING: "Hello from the environment"
  DEMO_FAREWELL: "Such a sweet sorrow"
---
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo-cm
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: demo
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      env:
        - name: DEMO_GREETING
          valueFrom:
            configMapKeyRef:
              name: sample-data
              key: DEMO_GREETING
        - name: DEMO_FAREWELL
          valueFrom:
            configMapKeyRef:
              name: sample-data
              key: DEMO_FAREWELL