apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
  DEMO_GREETING: SGVsbG8gZnJvbSB0aGUgZW52aXJvbm1lbnQ=
---

apiVersion: v1
kind: Pod
metadata:
  name: envar-demo-secret
  labels:
    purpose: demonstrate-secrets
spec:
  containers:
    - name: demo
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      env:
        - name: DEMO_GREETING
          valueFrom:
            secretKeyRef:
              name: sample-secret
              key: DEMO_GREETING
---